API_BASE = "http://httpbin.org"
DEFAULT_POLL_INTERVAL = 3
DEFAULT_POLL_TIMEOUT = 3600

PENDING = "PENDING"
ERRORED = "ERRORED"
COMPLETE = "COMPLETED"
VALID_STATUSES = [PENDING, ERRORED, COMPLETE]
TERMINAL_STATUSES = [COMPLETE, ERRORED]
